# Generated by Django 6.0.1 on 2026-02-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='issue',
            name='actual_completion',
            field=models.DateTimeField(blank=True, help_text='Actual completion date', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Admin's internal notes about the issue"),
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, help_text='Estimated completion date', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of resolution if applicable', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_details',
            field=models.TextField(blank=True, help_text='Detailed explanation of work done'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_evidence',
            field=models.TextField(blank=True, help_text='Evidence or proof of resolution'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='Summary of resolution for user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours spent on resolution', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='AdminWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('assessment', 'Initial Assessment'), ('investigation', 'Investigation'), ('repair', 'Repair Work'), ('maintenance', 'Maintenance'), ('coordination', 'Coordination'), ('documentation', 'Documentation'), ('follow_up', 'Follow-up'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Description of work performed')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Hours spent on this work', max_digits=5)),
                ('materials_used', models.TextField(blank=True, help_text='Materials or resources used')),
                ('outcome', models.TextField(help_text='Result or outcome of this work')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='issues_admi_created_a77c4b_idx'), models.Index(fields=['issue'], name='issues_admi_issue_i_7d6e8f_idx'), models.Index(fields=['admin'], name='issues_admi_admin_i_77bee6_idx')],
            },
        ),
    ]
