# Generated by Django 6.0.1 on 2026-02-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_resolutionevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Notes about current progress for user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='progress_status',
            field=models.CharField(default='not_started', help_text='Current progress status', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='progress_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When progress was last updated'),
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('milestone', 'Milestone Reached'), ('delay', 'Delay Reported'), ('issue', 'New Issue Found'), ('completion', 'Task Completed'), ('status', 'Status Update'), ('resource', 'Resource Update'), ('other', 'Other Update')], max_length=20)),
                ('progress_percentage', models.IntegerField(help_text='Progress percentage at this update (0-100)')),
                ('title', models.CharField(help_text='Brief title of this update', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of progress update')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps or planned actions')),
                ('estimated_completion', models.DateTimeField(blank=True, help_text='New estimated completion date', null=True)),
                ('is_major_update', models.BooleanField(default=False, help_text='Is this a major milestone update?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='issues_prog_created_d66d6c_idx'), models.Index(fields=['issue'], name='issues_prog_issue_i_006684_idx'), models.Index(fields=['admin'], name='issues_prog_admin_i_941936_idx'), models.Index(fields=['is_major_update'], name='issues_prog_is_majo_607291_idx')],
            },
        ),
    ]
