# Generated by Django 6.0.1 on 2026-02-26 12:53

import django.core.validators
import django.db.models.deletion
import security.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_issue_progress_notes_issue_progress_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the issue was soft deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted the issue",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Whether the issue is in trash"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="issue_attachments/%Y/%m/%d/",
                validators=[security.validators.validate_file_upload],
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="filename",
            field=models.CharField(
                max_length=255,
                validators=[security.validators.NoMaliciousContentValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                validators=[security.validators.NoMaliciousContentValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="description",
            field=models.TextField(
                validators=[security.validators.NoMaliciousContentValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="location",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_location",
                        message="Location can only contain letters, numbers, spaces, dots, commas, hyphens, and forward slashes.",
                        regex="^[a-zA-Z0-9\\s\\-\\.,\\/]{1,255}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[security.validators.NoMaliciousContentValidator()],
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["is_deleted"], name="issues_issu_is_dele_857426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["deleted_at"], name="issues_issu_deleted_63525d_idx"
            ),
        ),
    ]
