# Generated by Django 6.0.1 on 2026-02-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_add_soft_delete_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="issue",
            name="issues_issu_is_dele_857426_idx",
        ),
        migrations.AlterField(
            model_name="issue",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When issue was moved to trash", null=True
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this issue",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="issue",
            name="is_deleted",
        ),
    ]
