# Generated by Django 6.0.1 on 2026-03-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_is_anonymous'),
        ('issues', '0007_remove_issue_issues_issu_is_dele_857426_idx_and_more'),
    ]

    operations = [
    ]
