# Generated by Django 6.0.1 on 2026-03-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0010_issue_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("acknowledged", "Acknowledged"),
                            ("on_site", "Arrived On Site"),
                            ("diagnosis", "Diagnosis"),
                            ("in_progress", "Work In Progress"),
                            ("blocked", "Blocked - Needs Attention"),
                            ("completed", "Work Completed"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What was observed or done at this step"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo evidence for this log entry",
                        null=True,
                        upload_to="issue_progress/%Y/%m/%d/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issues_issu_deleted_63525d_idx",
        ),
        migrations.AddField(
            model_name="issue",
            name="blocker_note",
            field=models.TextField(
                blank=True,
                help_text="Explanation of what is blocking progress",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_blocked",
            field=models.BooleanField(
                default=False, help_text="Whether this issue is currently blocked"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the issue was verified by an admin",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who verified and closed the issue",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="resolution_summary",
            field=models.TextField(
                blank=True, help_text="Summary of resolution for user", null=True
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Pending"),
                    ("in-progress", "In Progress"),
                    ("awaiting_verification", "Awaiting Verification"),
                    ("resolved", "Resolved"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="issueprogresslog",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_logs",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issueprogresslog",
            name="staff",
            field=models.ForeignKey(
                help_text="Staff member who created this log entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_progress_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="issue",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="deleted_by",
        ),
        migrations.AddIndex(
            model_name="issueprogresslog",
            index=models.Index(
                fields=["-created_at"], name="issues_issu_created_90c7db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueprogresslog",
            index=models.Index(fields=["issue"], name="issues_issu_issue_i_226929_idx"),
        ),
        migrations.AddIndex(
            model_name="issueprogresslog",
            index=models.Index(fields=["staff"], name="issues_issu_staff_i_3a3cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="issueprogresslog",
            index=models.Index(
                fields=["log_type"], name="issues_issu_log_typ_3c9b79_idx"
            ),
        ),
    ]
