# Generated by Django 6.0.1 on 2026-03-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0011_issueprogresslog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this issue was assigned to the current assignee",
                null=True,
            ),
        ),
    ]
