# Generated by Django 6.0.1 on 2026-03-04 09:46

import security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0012_issue_assigned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueprogresslog",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo evidence for this log entry",
                null=True,
                upload_to="issue_progress/%Y/%m/%d/",
                validators=[security.validators.validate_file_upload],
            ),
        ),
    ]
