# Generated by Django 6.0.1 on 2026-03-04 11:03

import django.core.validators
import django.db.models.deletion
import security.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_alter_issueprogresslog_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('facilities', 'Facilities'), ('it-infrastructure', 'IT Infrastructure'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('equipment', 'Equipment'), ('safety', 'Safety'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50, unique=True)),
                ('response_time_hours', models.PositiveIntegerField(help_text='Target resolution time in hours for this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text='Whether this issue has exceeded its SLA without being resolved'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this issue is part of a recurring pattern for the same location and category'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text='When this issue is due according to SLA rules', null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[security.validators.NoMaliciousContentValidator()])),
                ('location', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_location', message='Location can only contain letters, numbers, spaces, dots, commas, hyphens, and forward slashes.', regex='^[a-zA-Z0-9\\s\\-\\.,\\/]{1,255}$')])),
                ('scheduled_for', models.DateTimeField(help_text='When this maintenance task is planned to occur')),
                ('notes', models.TextField(blank=True, validators=[security.validators.NoMaliciousContentValidator()])),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether the 24-hour reminder email has been sent to the assigned staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_issue', models.ForeignKey(blank=True, help_text='Optional related issue that motivated this maintenance task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='issues.issue')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
