# Generated by Django 6.0.1 on 2026-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0015_issuefeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ai_analyzed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this comment was last analyzed by AI",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="frustration_score",
            field=models.IntegerField(
                default=0, help_text="AI-calculated frustration score (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="needs_escalation",
            field=models.BooleanField(
                default=False,
                help_text="Whether this comment indicates need for escalation",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("frustrated", "Frustrated"),
                    ("angry", "Angry"),
                ],
                default="neutral",
                help_text="AI-detected sentiment from the comment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="ai_analyzed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this issue was last analyzed by AI",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="frustration_score",
            field=models.IntegerField(
                default=0, help_text="AI-calculated frustration score (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="needs_escalation",
            field=models.BooleanField(
                default=False,
                help_text="Whether this issue needs priority escalation based on AI analysis",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("frustrated", "Frustrated"),
                    ("angry", "Angry"),
                ],
                default="neutral",
                help_text="AI-detected sentiment from the issue description",
                max_length=20,
            ),
        ),
    ]
