# Generated by Django 6.0.1 on 2026-03-16 07:19

import datetime
import django.db.models.deletion
import security.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_comment_ai_analyzed_at_comment_frustration_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sla_breached',
            field=models.BooleanField(default=False, help_text='True if not resolved by sla_deadline'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='When this issue is due according to SLA rules starting from acknowledgement', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_paused_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Total time SLA was paused due to maintenance'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_reminded_2d',
            field=models.BooleanField(default=False, help_text='Tracks if 2-day reminder was sent'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_reminded_5d',
            field=models.BooleanField(default=False, help_text='Tracks if 5-day reminder was sent'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_reminded_day',
            field=models.BooleanField(default=False, help_text='Tracks if same-day reminder was sent'),
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[security.validators.NoMaliciousContentValidator()])),
                ('description', models.TextField(validators=[security.validators.NoMaliciousContentValidator()])),
                ('scheduled_start', models.DateTimeField(help_text='When maintenance begins')),
                ('scheduled_end', models.DateTimeField(help_text='When maintenance is planned to end')),
                ('actual_end', models.DateTimeField(blank=True, help_text='Set if admin ends maintenance early', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='True when system is currently in maintenance')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_48h', models.BooleanField(default=False, help_text='Tracks if 48hr warning was sent')),
                ('notified_24h', models.BooleanField(default=False, help_text='Tracks if 24hr warning was sent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
    ]
