# Generated by Django 6.0.1 on 2026-03-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_issue_sla_breached_issue_sla_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sla_pause_start',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the SLA was paused due to maintenance', null=True),
        ),
    ]
