# Generated by Django 6.0.1 on 2026-03-26 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0020_feedbacktoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="is_trashed",
            field=models.BooleanField(default=False, help_text="Soft-deleted by user"),
        ),
        migrations.AddField(
            model_name="issue",
            name="trashed_at",
            field=models.DateTimeField(blank=True, help_text="When trashed", null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="trashed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trashed_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
