# Generated by Django 6.0.1 on 2026-03-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0021_issue_is_trashed_issue_trashed_at_issue_trashed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="is_trashed",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="trashed_at",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="trashed_by",
        ),
    ]
