# Generated by Django 6.0.1 on 2026-03-18 06:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_issue_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_maintenance_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 18, 6, 29, 11, 916513, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
