# Generated by Django 6.0.1 on 2026-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_used_passwordresettoken_is_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
