# Generated by Django 6.0.1 on 2026-03-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
