# Generated by Django 6.0.1 on 2026-02-26 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="type",
            new_name="notification_type",
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_on_comment", models.BooleanField(default=True)),
                ("email_on_status_change", models.BooleanField(default=True)),
                ("email_on_assignment", models.BooleanField(default=True)),
                ("email_on_upvote", models.BooleanField(default=False)),
                ("email_on_resolution", models.BooleanField(default=True)),
                ("real_time_notifications", models.BooleanField(default=True)),
                ("daily_digest", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
