# Generated by Django 6.0.1 on 2026-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_announcement_announcementdismissal"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("error_message", models.TextField()),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("retry_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-attempted_at"],
            },
        ),
    ]
