# Generated by Django 6.0.1 on 2026-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_failedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_issue_updates",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_maintenance_alerts",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="daily_digest",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email_on_assignment",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email_on_comment",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email_on_resolution",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email_on_status_change",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="email_on_upvote",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="real_time_notifications",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
