# Generated by Django 6.0.1 on 2026-03-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationpreference_email_issue_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('staff', 'Staff Only'), ('students', 'Students Only')], default='all', help_text='Who should see this announcement.', max_length=10),
        ),
    ]
